// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"mycc/internal/handler"
	"mycc/internal/router"
)

// Injectors from wire.go:

// InitializeRouter 使用 Wire 自动注入依赖创建 Router
func InitializeRouter() *router.Router {
	dateHandler := handler.NewDateHandler()
	routerRouter := router.NewRouter(dateHandler)
	return routerRouter
}
